name: khushboo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.4.1
  clip_shadow: ^0.2.1
  flutter_custom_clippers: ^1.1.1
  confetti: ^0.5.2
  flutter_icons: ^1.1.0
  flutter_speed_dial: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/favourites/
    - assets/solo/
    - assets/chats/
    - assets/miscellaneous/
  fonts:
    - family: Mochiy
      fonts:
        - asset: fonts/MochiyPopPOne-Regular.ttf